export const UK_UNIVERSITIES: string[] = [
  "Aberystwyth University",
  "Anglia Ruskin University",
  "Arden University",
  "Arts University Bournemouth",
  "Aston University",
  "Bangor University",
  "Bath Spa University",
  "Birmingham City University",
  "Bishop Grosseteste University",
  "Bournemouth University",
  "Brunel University London",
  "Buckinghamshire New University",
  "Canterbury Christ Church University",
  "Cardiff Metropolitan University",
  "Cardiff University",
  "City, University of London",
  "Coventry University",
  "Cranfield University",
  "De Montfort University",
  "Durham University",
  "Edge Hill University",
  "Edinburgh Napier University",
  "Falmouth University",
  "Glasgow Caledonian University",
  "Goldsmiths, University of London",
  "Harper Adams University",
  "Heriot-Watt University",
  "Imperial College London",
  "Keele University",
  "King's College London",
  "Kingston University",
  "Lancaster University",
  "Leeds Arts University",
  "Leeds Beckett University",
  "Leeds Trinity University",
  "Liverpool Hope University",
  "Liverpool John Moores University",
  "London Metropolitan University",
  "London School of Economics and Political Science",
  "London South Bank University",
  "Loughborough University",
  "Manchester Metropolitan University",
  "Middlesex University",
  "Newcastle University",
  "Newman University",
  "Northumbria University",
  "Norwich University of the Arts",
  "Nottingham Trent University",
  "Open University",
  "Oxford Brookes University",
  "Plymouth Marjon University",
  "Queen Margaret University",
  "Queen Mary University of London",
  "Queen's University Belfast",
  "Ravensbourne University London",
  "Robert Gordon University",
  "Roehampton University",
  "Royal Academy of Music",
  "Royal College of Art",
  "Royal Holloway, University of London",
  "Sheffield Hallam University",
  "SOAS University of London",
  "Solent University",
  "St George's, University of London",
  "St Mary's University, Twickenham",
  "Staffordshire University",
  "Swansea University",
  "Teesside University",
  "The University of Edinburgh",
  "The University of Manchester",
  "The University of Sheffield",
  "UCL (University College London)",
  "Ulster University",
  "University College Birmingham",
  "University of Aberdeen",
  "University of Bath",
  "University of Bedfordshire",
  "University of Birmingham",
  "University of Bolton",
  "University of Bradford",
  "University of Brighton",
  "University of Bristol",
  "University of Buckingham",
  "University of Cambridge",
  "University of Central Lancashire",
  "University of Chester",
  "University of Chichester",
  "University of Cumbria",
  "University of Derby",
  "University of Dundee",
  "University of East Anglia",
  "University of East London",
  "University of Essex",
  "University of Exeter",
  "University of Glasgow",
  "University of Gloucestershire",
  "University of Greenwich",
  "University of Hertfordshire",
  "University of Huddersfield",
  "University of Hull",
  "University of Kent",
  "University of Law",
  "University of Leeds",
  "University of Leicester",
  "University of Lincoln",
  "University of Liverpool",
  "University of London",
  "University of Northampton",
  "University of Nottingham",
  "University of Oxford",
  "University of Plymouth",
  "University of Portsmouth",
  "University of Reading",
  "University of Roehampton",
  "University of Salford",
  "University of South Wales",
  "University of Southampton",
  "University of St Andrews",
  "University of Stirling",
  "University of Strathclyde",
  "University of Suffolk",
  "University of Sunderland",
  "University of Surrey",
  "University of Sussex",
  "University of the Arts London",
  "University of the Highlands and Islands",
  "University of the West of England",
  "University of the West of Scotland",
  "University of Wales Trinity Saint David",
  "University of Warwick",
  "University of West London",
  "University of Westminster",
  "University of Winchester",
  "University of Wolverhampton",
  "University of Worcester",
  "University of York",
  "Wrexham Glyndwr University",
  "York St John University",
  "Other",
];
